config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get  '/about', to: 'static_pages#about'
  get '/search', to: 'static_pages#search'
  get '/search_result', to: 'static_pages#search_result'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  #get '/user/show/:id' => 'users#show'
  resources :users, :only => [:show]
  resources :places
  resources :reviews
  root to: 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
  def search
    @q = Place.ransack(params[:q])
    @places = @q.result.includes(:service)
  end
  def self.get_newest_list_review
    list_data = []
    length_list = 0
    Review.all.reverse.each do |review|
      if review.created_at - 20.day.ago > 0
        list_data.push(review)
        length_list += 1
      end
      if length_list == 10
        return list_data
      end
    end
    list_data
  end
# get 10 newest place
  def self.get_list_registration
    list_data = []
    length_list = 0
    Place.all.reverse.each do |place|
      if place.created_at - 3.day.ago > 0
        list_data.push(place)
        length_list += 1
      end
      if length_list == 5
        return list_data
      end
    end
    list_data
  end

  def self.get_top (array_ag, result_length)
    result_data = []
    if array_ag.length >= (5 - result_length)
      (result_length..4).each { |i|
        result_data.push(array_ag[i - result_length])
      }
      result_data
    else
      array_ag
    end
  end

#get top10 rating
  def self.get_list_rating
    list_data = {list1: [], list2: [], list3: [], list4: [], list5: []}
    result_data = []
    Place.all.each do |place|
      x = place.mediumRating
      if (0 <= x) && (x < 1)
        list_data[:list5].push(place)
      elsif (1 <= x) && (x < 2)
        list_data[:list4].push(place)
      elsif (2 <= x) && (x < 3)
        list_data[:list3].push(place)
      elsif (3 <= x) && (x < 4)
        list_data[:list2].push(place)
      elsif (4 <= x) && (x <= 5)
        list_data[:list1].push(place)
      end
    end
    list_data.each do |key, value|
      if result_data.length == 5
         return result_data
      else
        (value.sort_by! { |data| data.mediumRating }).reverse!
        result_data.concat get_top(value, result_data.length)
      end
    end
    result_data
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="col-md-5 list-places-registration">
    <div class="banner">
      <div class="nameList"><strong title="10 newest place since 3 day ago">10 Newest Places</strong></div>
      <ul class="list-group data-list-places ">
        <% StaticPagesController.get_list_registration.each do |place| %>
          <li class="list-group-item ">
            <ul class="list-group">
              <li class="list-group-item list-group-item-primary key-value-first">
                <div class="name-place"><%= link_to place.name, place_path(place.id), class: 'key-first' %>
                </div>
              </li>
              <li class="list-group-item key-value">
                <div><strong class="key">Service</strong>
                  <span class="value"><%= place.service.name %></span>
                </div>
              </li>
              <li class="list-group-item key-value">
                <div><strong class="key">MediumRating</strong>
                  <span class="value"><%= place.mediumRating %></span>
                </div>
              </li>
              <li class="list-group-item key-value">
                <div><strong class="key">Number Reviews</strong>
                  <span class="value"><%= place.reviews.count %></span>
                </div>
              </li>
              <li class="list-group-item key-value">
                <div><strong class="key">Address</strong>
                  <span class="value"><%= place.address %></span>
                </div>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-md-5 list-places-ratings">
    <div class="banner">
      <div class="nameList"><strong title="Top 10 rating place">Top 10 Place</strong></div>
      <ul class="list-group data-list-places">
        <% StaticPagesController.get_list_rating.each do |place| %>
          <li class="list-group-item ">
            <ul class="list-group">
              <li class="list-group-item list-group-item-primary">
                <div class="name-place"><%= link_to place.name, place_path(place.id) %></div>
              </li>
              <li class="list-group-item key-value">
                <div><strong class="key">Service</strong>
                  <span class="value"><%= place.service.name %></span>
                </div>
              </li>
              <li class="list-group-item key-value">
                <div><strong class="key">MediumRatings</strong>
                  <scan class="value"><%= place.mediumRating %></scan>
                </div>
              </li>
              <li class="list-group-item key-value">
                <div><strong class="key">Number Reviews</strong>
                  <scan class="value"><%= place.numberRatings %></scan>
                </div>
              </li>
              <li class="list-group-item key-value">
                <div><strong class="key">Address</strong>
                  <scan class="value"><%= place.address %></scan>
                </div>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-md-2 ">
    <div class="name-list-review" id="name-home-review"><strong title="10 newest reviews">Reviews</strong></div>
    <ul class="list-group data-list-review ">
      <% StaticPagesController.get_newest_list_review.each do |review| %>
        <li class="list-group-item ">
          <div class="list-notice">
            <%= link_to review.place.name, place_path(review.place), class: "review-place",
                        title: "More information about this place" %>
            <%= link_to "be reviewed by", review_path(review), class: "review-text-notice",
                        title: "More information" %>
            <%= link_to review.user.name, user_path(review.user),
                        class: "review-user", title: "More information about this place" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/static_pages/search.html.erb
<div class="row">
  <div class="col-md-10 offset-md-1 ">
    <div class="sort_by">
      <span>Sort_by:</span>
      <%= sort_link(@q, :name, 'Name', default_order: :desc) %>
      <%= sort_link(@q, :mediumRating, 'medium-Rating', default_order: :desc) %>
      <%= sort_link(@q, :numberRatings, 'number-Ratings', default_order: :desc) %>
    </div>
    <%= search_form_for @q, url: search_path, method: 'get', class: "form-inline" do |f| %>

      <div class="row">
        <div class="form-group mb-2 ml-1">
          <%= f.search_field :name_cont, class: "form-control", placeholder: "name" %>
        </div>
        <div class="form-group mb-2 ml-1">
          <%= f.search_field :address_cont, class: "form-control", placeholder: "address" %>
        </div>
        <div class="form-group mb-2 ml-1">
          <%= f.search_field :phoneNumber_cont, class: "form-control", placeholder: "phoneNumber" %>
        </div>
        <div class="form-group mb-2 ml-1">
          <%= f.search_field :mediumRating_eq, class: "form-control", placeholder: "4.0" %>
        </div>
        <div class="form-group mb-2 ml-1">
          <%= f.select :service_name_eq, options_for_select([['Select', ''],
                                                             ['amusement park', 'amusement park'],
                                                             ['restaurant', 'restaurant'],
                                                             ['resort', 'resort'],
                                                             ['shop', 'shop'],
                                                             ['shopping mall', 'shopping mall']
                                                            ]), {}, {class: "form-control"} %>
        </div>
        <%= f.submit class: "btn btn-primary mb-2" %>
      </div>

    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Service</th>
        <th scope="col">NumberRatings</th>
        <th scope="col">Medium-Rating</th>
        <th scope="col">PhoneNumber</th>
        <th scope="col">Address</th>
        <th scope="col">Action</th>
      </tr>
      </thead>
      <tbody>
      <% i = 0 %>
      <% @places.each do |place| %>
        <tr>
          <th scope="row"><%= i %></th>
          <td><%= place.name %></td>
          <td><%= place.service.name %></td>
          <td><%= place.numberRatings %></td>
          <td><%= place.mediumRating %></td>
          <td><%= place.phoneNumber %></td>
          <td class="des-search"><%= place.address %></td>
          <% if current_user.role == 'Reviewer' %>
            <td>
              <% status = -1 %>
              <% if place.reviews.each do |review| %>
                <% if review.user == current_user %>
                  <% status = review.id %>
                <% end %>
              <% end %>
              <% end %>
              <% if status != -1 %>
                <%= link_to 'edit your review', edit_review_path(status) %>
              <% else %>
                <%= link_to 'make your review', place_path(place) %>
              <% end %>
            </td>
          <% else %>
            <td>
              <%= link_to 'show more', place_path(place), id: "show-more-search" %>
            </td>

          <% end %>
        </tr>
        <% i += 1 %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/static_pages/search_result.html.erb
<div class="row">
  <div class="col-md-6">
    <%= search_form_for @q, url: search_result_path, html: { method: :get } do |f|%>
      <%= f.label :name %>
      <%= f.search_field :name %>
      <%= f.submit %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Service</th>
        <th scope="col">NumberRatings</th>
        <th scope="col">Medium-Rating</th>
        <th scope="col">PhoneNumber</th>
        <th scope="col">Description</th>
      </tr>
      </thead>
      <tbody>
      <% i = 0 %>
      <% @place.each do |place| %>
        <tr>
          <th scope="row"><%= i %></th>
          <td><%= place.name %></td>
          <td><%= place.service.name %></td>
          <td><%= place.numberRatings %></td>
          <td><%= place.mediumRating %></td>
          <td><%= place.phoneNumber %></td>
          <td class="des-search"><%= place.description %></td>
        </tr>
        <% i += 1 %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>