config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get  '/about', to: 'static_pages#about'
  get '/search', to: 'static_pages#search'
  get '/search_result', to: 'static_pages#search_result'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  #get '/user/show/:id' => 'users#show'
  resources :users, :only => [:show]
  resources :places
  resources :reviews
  root to: 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
    @user = current_user
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    # @review = Review.new
    redirect_to search_path
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params.merge!(user_id: current_user.id))
    hash_value = review_params.merge(type: 1)
    @place = Place.find_by(id: hash_value[:place_id])
    respond_to do |format|
      if  @review.save && @place.increase_rating(hash_value)
        @place.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :show }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    hash_value = {type: 2, review_id: @review.id, rating: review_params_update[:rating],
                  place_id: @review.place.id}
    @place = Place.find_by(id: hash_value[:place_id])
    respond_to do |format|
      if @place.increase_rating(hash_value) && @review.update(review_params_update)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def review_params
    # params.fetch(:review, {})
    params.require(:review).permit(:place_id, :rating, :comment)
  end

  def review_params_update
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/_form_new_review.html.erb
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">
  Make your review
</button>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New review for <%= @place.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for :review, url: "/reviews", method: "post" do |f| %>
          <div class="form-group">
            <%= f.label :place_id, class: "col-form-label" %>
            <%= f.text_field :place_id, value: "#{@place.id}", class: "form-control", readonly: true %>
          </div>
          <div class="form-group">
            <%= f.label :rating, class: "col-form-label" %>
            <%= f.select :rating, [1, 2, 3, 4, 5], {}, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :comment, class: "col-form-label" %>
            <%= f.text_area :comment, class: "form-control" %>
          </div>
          <%= f.submit class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_menubar.html.erb
<div class="container">
  <div class="">
    <div class="dropdown col-md-2 offset-md-10 menu-action">
      <button type="button" class="btn btn-primary dropdown-toggle button-manage" data-toggle="dropdown">
        Manage Reviews
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="/reviews">Manage</a>
        <a class="dropdown-item" href="/reviews/new">New Review</a>
        <% if @review != nil && @review.comment != nil %>
          <a class="dropdown-item" href="/reviews/<%= @review.id%>/edit">Edit Review</a>
          <a class="dropdown-item" href="/reviews/<%= @review.id%>">Show Review</a>
          <a class="dropdown-item" href="/reviews/new"></a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/edit.html.erb
<%= render 'menubar' %>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="topic"><h2>Edit Review</h2></div>
    <%= form_for(@review, url: review_path(@review), html: {method: :put}) do |f| %>
      <%= render "devise/shared/error_messages", resource: f.object %>

      <div class="form-group">
        <%= f.label :rating %>
        <%= f.select :rating, [1, 2, 3, 4, 5], {}, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :comment %>
        <%= f.text_area :comment, class: "form-control", placeholder: "content",size: "30x10" %>
      </div>
      <%= f.submit "Update", class: "btn btn-primary" %>

    <% end %>

  </div>
</div>

app/views/reviews/index.html.erb
<% if @user.role == "Reviewer" %>
  <%= render 'menubar' %>
  <main role="main" class="container">
    <div class="my-3 p-3 bg-white rounded box-shadow">
      <h4 class="border-bottom border-gray pb-2 mb-0">Manage your review-paper</h4>
      <ul class="list-places">
        <% @user.reviews.each do |review| %>
          <li>
            <div class="media text-muted pt-3">
              <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" style="width: 32px; height: 32px;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16c514ba710%20text%20%7B%20fill%3A%23007bff%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A2pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16c514ba710%22%3E%3Crect%20width%3D%2232%22%20height%3D%2232%22%20fill%3D%22%23007bff%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2211.0390625%22%20y%3D%2217.2%22%3E32x32%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
              <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <span class="list-in">
                  <strong class="d-block text-gray-dark ">
                  <%= link_to review.place.name, place_path(review.place) %>
                  </strong>
                </span>
                <span class="list-in link-in">
                  <strong class="d-block text-gray-dark ">
                  <%= link_to 'Destroy', review, method: :delete, data: {confirm: 'Are you sure?'} %>
                  </strong>
                </span>
                <span class="list-in link-in">
                  <strong class="d-block text-gray-dark ">
                    <%= link_to "Edit", edit_review_path(review.id) %>
                  </strong>
                </span>
                <span class="list-in link-in">
                  <strong class="d-block text-gray-dark ">
                    <%= link_to "More details", review_path(review.id) %>
                  </strong>
                </span>
                <strong class="d-block text-gray-dark"> <%= review.comment %></strong>
              </p>
            </div>
          </li>
        <% end %>
        <small class="d-block text-right mt-3">
          <%= link_to "Make new review-paper", new_review_path, id: "link-new-place" %>
        </small>
      </ul>
    </div>
  </main>
<% end %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<% if @review.user == current_user %>
  <%= render 'menubar' %>
<% end %>
<main role="main" class="container">
  <div class="my-3 p-3 bg-white rounded box-shadow">
    <h4 class="border-bottom border-gray pb-2 mb-0 title-table">Information Review</h4>
    <table class="table">
      <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Attribute</th>
        <th scope="col">Value</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <th scope="row">1</th>
        <td>id</td>
        <td><%= @review.id %></td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td>author</td>
        <td><%= link_to @review.user.name, user_path(@review.user) %></td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td>rating</td>
        <td><%= @review.rating %></td>
      </tr>
      <tr>
        <th scope="row">4</th>
        <td>content</td>
        <td><%= @review.comment %></td>
      </tr>
      </tbody>
    </table>
  </div>
  <% if current_user == @review.user %>
    <div class="btn-group link-of-show-places"  role="group">
      <a href="<%= edit_review_path(@review) %>" class=" btn btn-info btn-secondary " role="button">Edit Review</a>
      <a href="<%= reviews_path %>" class="btn btn-info btn-secondary" role="button">All Reviews</a>
    </div>
  <% end %>

</main>