config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get  '/about', to: 'static_pages#about'
  get '/search', to: 'static_pages#search'
  get '/search_result', to: 'static_pages#search_result'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'}
  #get '/user/show/:id' => 'users#show'
  resources :users, :only => [:show]
  resources :places
  resources :reviews
  root to: 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  belongs_to :service
  has_many :photos
  has_many :reviews
  # For use case when want to find places by service. so use has_and_belongs_to_many
  # has_and_belongs_to_many :services
  # But if just want to find services of a place so use has many, belongs_to
  has_many :services
  has_many_attached :images
  validates :name, presence: true, length: {maximum: 30}
  validates :address, presence: true
  validates :numberRatings, presence: true
  validates :mediumRating, presence: true
  validates :phoneNumber, presence: true

  validates :description, presence: true, length: {minimum: 20}

  public

  def increase_rating(hash_value)
    if hash_value[:type] == 1 # new review
      self.numberRatings += 1
      self.mediumRating *= ((self.numberRatings - 1).to_f / self.numberRatings)
      self.mediumRating += hash_value[:rating].to_f / self.numberRatings
    elsif hash_value[:type] == 2 # edit review
      review = Review.find_by(id: hash_value[:review_id])
      self.mediumRating += ((hash_value[:rating].to_f - review.rating).to_f / self.numberRatings)
    end
    self.save
  end

  def find_same_type_place
    service = self.service
    result = []
    Place.all.each do |place|
      unless place.id == self.id
        if service == place.service
          result.push(place)
        end
      end
    end
    result.sort_by! { |place| place.mediumRating }.reverse!
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :require_role_company, only: [:index]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /places
  # GET /places.json
  def index
    @places = Place.all
    @user = current_user
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params.merge(user_id: current_user.id, numberRatings: 0, mediumRating: 0 ))

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      user = User.find_for_authentication(email: current_user.email)
      if !user.valid_password?(params[:place][:current_password])
        flash[:danger] = "Check your password!"
        format.html { redirect_to edit_place_path(@place)}
      elsif @place.update(place_params_update.except(:current_password))
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name,:address,:phoneNumber, :description, :service_id)
    end
  def place_params_update
    params.require(:place).permit(:name,:address,:phoneNumber, :description, :current_password, images: [])
  end
  def correct_user
    redirect_to root_path flash[:danger] = "This place is not belong to you" unless current_user == @place.user
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/_menubar.html.erb
<div class="row">
  <div class="dropdown col-md-2 offset-md-10 menu-action">
    <button type="button" class="btn btn-primary dropdown-toggle button-manage" data-toggle="dropdown">
      Manage Places
    </button>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="/places">Manage</a>
      <a class="dropdown-item" href="/places/new">New Place</a>
      <% if @place != nil && @place.name != nil %>
        <a class="dropdown-item" href="/places/<%= @place.id %>/edit">Edit Place</a>
        <a class="dropdown-item" href="/places/<%= @place.id %>">Show Place</a>
        <a class="dropdown-item" href="/places/new"></a>
      <% end %>
    </div>
  </div>
</div>

app/views/places/edit.html.erb
<%= render 'menubar' %>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="topic"><h2>Edit Place</h2></div>
    <%= form_for(@place, url: place_path(@place), html: {method: :put}) do |f| %>
      <%= render "devise/shared/error_messages", resource: f.object %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", placeholder: "Your name" %>
      </div>
      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_area :address, class: "form-control", placeholder: "Your address" %>
      </div>
      <div class="form-group">
        <%= f.label :phoneNumber %>
        <%= f.telephone_field :phoneNumber, class: "form-control", placeholder: "Your phoneNumber" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", size: "30x10" %>
      </div>
      <div class="form-group">
        <%= f.label :images %>
        <%= f.file_field :images, class: "form-control", multiple: true %>
      </div>

      <div class="form-group">
        <%= f.label :current_password %>
        <%= f.password_field :current_password, autocomplete: "current-password", class: "form-control", placeholder: "Enter current password" %>
        <small>We need your current password to confirm your changes</small>
      </div>

      <%= f.submit "Update", class: "btn btn-primary" %>

    <% end %>

  </div>
</div>

app/views/places/index.html.erb
<% if @user.role == "Company" %>
  <%= render 'menubar' %>
  <main role="main" class="container">
    <div class="my-3 p-3 bg-white rounded box-shadow">
      <h4 class="border-bottom border-gray pb-2 mb-0">Manage your places</h4>
      <ul class="list-places">
        <% @user.places.each do |place| %>
          <li>
            <div class="media text-muted pt-3">
              <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" style="width: 32px; height: 32px;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16c514ba710%20text%20%7B%20fill%3A%23007bff%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A2pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16c514ba710%22%3E%3Crect%20width%3D%2232%22%20height%3D%2232%22%20fill%3D%22%23007bff%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2211.0390625%22%20y%3D%2217.2%22%3E32x32%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
              <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <span class="list-in"><strong class="d-block text-gray-dark "> <%= place.name %></strong></span>
                <span class="list-in link-in"><strong class="d-block text-gray-dark "><%= link_to 'Destroy', place, method: :delete, data: {confirm: 'Are you sure?'} %></strong></span>
                <span class="list-in link-in"><strong class="d-block text-gray-dark "><%= link_to "Edit", edit_place_path(place.id) %></strong></span>
                <span class="list-in link-in"><strong class="d-block text-gray-dark "><%= link_to "More details", place_path(place.id) %></strong></span>
                <strong class="d-block text-gray-dark"> <%= place.address %></strong>
              </p>
            </div>
          </li>
        <% end %>
        <small class="d-block text-right mt-3">
          <%= link_to "Register new place", new_place_path,id: "link-new-place" %>
        </small>
      </ul>
    </div>
  </main>
<% end %>

app/views/places/new.html.erb
<%= render 'menubar' %>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="topic"><h2>New Place</h2></div>
    <%= form_for(@place, url: places_path(@place), html: {method: :post}) do |f| %>
      <%= render "devise/shared/error_messages", resource: f.object %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", placeholder: "Your name" %>
      </div>
      <div class="form-group">
        <%= f.label :service_id %>
        <%= f.select(:service_id, Service.all.collect { |review| [review.name, review.id] }, {}, {class: 'form-control'}) %>
      </div>

      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_area :address, class: "form-control", placeholder: "Your address" %>
      </div>
      <div class="form-group">
        <%= f.label :phoneNumber %>
        <%= f.telephone_field :phoneNumber, class: "form-control", placeholder: "Your phoneNumber" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", size: "30x7" %>
      </div>

      <%= f.submit "Create", class: "btn btn-primary" %>

    <% end %>

  </div>

</div>

app/views/places/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="image-place">
      <div id="carouselExampleIndicators" class="carousel slide images-place" data-ride="carousel">
        <ol class="carousel-indicators">
          <% (0..(@place.images.count - 1)).each { |i| %>
            <% if i == 0 %>
              <li data-target="#carouselExampleIndicators" data-slide-to="<%= i %>" class="active"></li>
            <% else %>
              <li data-target="#carouselExampleIndicators" data-slide-to="<%= i %>"></li>
            <% end %>
          <% } %>
        </ol>
        <div class="carousel-inner">
          <% i = 0 %>
          <% @place.images.each do |image| %>
            <% if i == 0 %>
              <div class="carousel-item active">
                <%= image_tag image, alt: "#{i} slide" %>
              </div>
              <% i += 1 %>
            <% else %>
              <div class="carousel-item">
                <%= image_tag image, alt: "#{i} slide" %>
              </div>
            <% end %>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <% if @place.user == current_user %>
    <%= render 'menubar' %>
  <% end %>
</div>

<main role="main" class="container-fluid">
  <div class="row">
    <div class="bg-white rounded box-shadow w-100">
      <h4 class="border-bottom border-gray title-table">Information about <%= @place.name %></h4>
      <table class="table">
        <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Attribute</th>
          <th scope="col">Value</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <th scope="row">1</th>
          <td class="place-att">id</td>
          <td><%= @place.id %></td>
        </tr>
        <tr>
          <th scope="row">2</th>
          <td class="place-att">name</td>
          <td><%= @place.name %></td>
        </tr>
        <tr>
          <th scope="row">3</th>
          <td class="place-att">address</td>
          <td><%= @place.address %></td>
        </tr>
        <tr>
          <th scope="row">4</th>
          <td class="place-att">service</td>
          <td><%= @place.service.name %></td>
        </tr>
        <tr>
          <th scope="row">5</th>
          <td class="place-att">phone-number</td>
          <td><%= @place.phoneNumber %></td>
        </tr>
        <tr>
          <th scope="row">6</th>
          <td class="place-att">time-open</td>
          <td><%= @place.timeOpen.to_s + ' to ' + @place.timeClose.to_s %></td>
        </tr>
        <tr>
          <th scope="row">7</th>
          <td class="place-att">description</td>
          <td><%= @place.description %></td>
        </tr>
        <tr>
          <th scope="row">8</th>
          <td class="place-att">number-ratings</td>
          <td><%= @place.numberRatings %></td>
        </tr>
        <tr>
          <th scope="row">9</th>
          <td class="place-att">medium-rating</td>
          <td><%= @place.mediumRating %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <% if current_user == @place.user %>
      <div class="btn-group link-of-show-places w-100" role="group">
        <a href="<%= edit_place_path(@place) %>" class=" btn btn-info btn-secondary " role="button">Edit Place</a>
        <a href="<%= places_path %>" class="btn btn-info btn-secondary" role="button">All Place</a>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="bg-white rounded box-shadow w-100">
      <h4 class="border-bottom border-gray pb-2 mb-0 title-table">All review-paper about <%= @place.name %></h4>
      <table class="table table-review">
        <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Id</th>
          <th scope="col">Author</th>
          <th scope="col">Rating</th>
          <th scope="col">Content</th>
          <th scope="col">Link</th>
        </tr>
        </thead>
        <tbody>
        <% i = 1 %>
        <% @place.reviews.each do |review| %>
          <tr>
            <th scope="row"><%= i %></th>
            <td><%= review.id %></td>
            <td><%= link_to review.user.name, user_path(review.user) %></td>
            <td><%= review.rating %></td>
            <td id="comment"><%= review.comment %></td>
            <td><%= link_to "Show more", review_path(review.id), class: "showmore" %></td>
          </tr>
          <% i += 1 %>
        <% end %>

        </tbody>
      </table>
      <% if current_user.role == "Reviewer" %>
      <div class="col-md-2 offset-md-10">
        <% review = Review.find_by(user_id: current_user.id,place_id: @place.id)%>
        <% if current_user.reviews.include? review %>
          <button class="btn btn-primary button-edit-review" title="you used to review this place">
            <%= link_to "Edit your review",edit_review_path(review) %>
          </button>
        <% else %>
          <%= render 'reviews/form_new_review' %>
        <% end %>
      </div>
        <% end %>

    </div>
  </div>
  <div class="row">
    <div class=" bg-white rounded box-shadow w-100">
      <h4 class="border-bottom border-gray pb-2 mb-0 title-table">Similar Places</h4>
      <table class="table">
        <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">MediumRating</th>
          <th scope="col">NumberRatings</th>
          <th scope="col">Company</th>
        </tr>
        </thead>
        <tbody>
        <% i = 1 %>
        <% @place.find_same_type_place.each do |place| %>
          <tr>
            <th scope="row"><%= i %></th>
            <td><%= link_to place.name, place_path(place) %></td>
            <td><%= place.mediumRating %></td>
            <td><%= place.numberRatings %></td>
            <td><%= link_to place.user.name, user_path(place.user) %></td>
          </tr>
          <% i += 1 %>
        <% end %>

        </tbody>
      </table>
    </div>
  </div>
</main>